### ISSUE TITLE
personal suggestion

### ISSUE THREAD

**Issue by pandaro** [bosapara/heads#1]
I like a lot this mod, really!
i will to suggest to add a option:
i a pvp game disable head craft and add a "on player dead" callback to obtain a head.
EXAMPLE:
player 1 kill player 2 -> player 1 obtain a head, player 2 loose his head.
heads can use as a server admin will
thanks for your time

**Comment by bosapara** [comment]
Agree with it. But there are 2 problems: 

1. Need to delete skin change on punch, if head will drop after death. (it will change mod)
2. How to add name/description of dropped head instead of default name "Head Number .."?

**Comment by pandaro** [comment]
2: name decription can be added via itemstack metadata like: stack:get_meta() and meta:set_string()
and is not fully necessary know the name of the player that lose the heads; the major thing is that a player that have lose a head cannot loose another head and this is doable via:

player:get_meta()
meta:set_bool('head', false)
but a player that have lose her head can re obtain the head by killing another player
player:get_meta()
meta:set_bool('head', true)
1:is a different mod?

**Comment by bosapara** [comment]
1. Mod replaced with new idea, old idea of change head skins can't be interest.
2. Now need to find out how fix 'after_dig_node' func. (on_place works good) and how to make correctly head spawn only when player was killed (not just died).
